# Generated by Django 4.0.1 on 2022-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
