# Generated by Django 4.0.1 on 2022-02-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
