# Generated by Django 4.0.1 on 2022-02-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsstory_category_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('General', 'General'), ('Career', 'Career')], max_length=200),
        ),
    ]
