# Generated by Django 4.0.1 on 2022-02-18 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_newsstory_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
